### ISSUE TITLE
Travis buddy still comments on success even though I set

### ISSUE THREAD

**Issue by medyagh** [bluzi/travis-buddy#153]
it used to work fine, I did some changes in my travis yaml and since then travis buddy comments on success:

here is the full travis yaml

https://github.com/kubernetes/minikube/blob/115fc4fd9507a97e3428bbfe57c393ef8510fcff/.travis.yml

which has this in the end
```
notifications:
    webhooks: https://www.travisbuddy.com/
    on_success: never # travisbuddy don't comment on successful 
```

any idea how I can make it not comment on success ?

**Comment by bluzi** [comment]
Hello,

That looks like a bug in TravisCI or a misconfiguration on your side, since `on_success: never` should tell TravisCI to never trigger notifications for successful builds. 

That said, TravisBuddy has a way of handling this, you can use the `only` query parameter, like this:

```
notifications:
    webhooks: https://www.travisbuddy.com?only=failed,errored
    on_success: never # travisbuddy don't comment on successful 
```

This will tell TravisBuddy to create comments only for builds with status `failed` or `errored`.

Let me know if it helps

**Comment by medyagh** [comment]
thank you for such a fast response ! that does sound like a Travis-ci's fault that should have not even pinged travis-buddy.

its good that travis buddy has a filter for it.

**Comment by bluzi** [comment]
You're welcome, TravisCI has several issues like that and I feel like being able to handle those issues is part of TravisBuddy's job :)
