### ISSUE TITLE
Question about functionality

### ISSUE THREAD

**Issue by kenman345** [bluzi/travis-buddy#61]
I gave your travisBuddy a try here: https://github.com/acceptbitcoincash/acceptbitcoincash/pull/699#issuecomment-374276876

It outpout a ton of the log even though it was able to  identify that the "rake" command is what failed the build. So why did it output so much of the logs?

**Comment by bluzi** [comment]
That's a bug. 
This is the log of the failed build: https://api.travis-ci.org/v3/job/355449814/log.txt

I wonder where TravisBuddy found the text in the comment.
I'll have check and get back to you, but know that the log will be much shorter.

**Comment by kenman345** [comment]
https://github.com/acceptbitcoincash/acceptbitcoincash/pull/758#issuecomment-375743788

got a similar output this time too

**Comment by kenman345** [comment]
I see you forked our repository, Hopefully you're finding something

**Comment by bluzi** [comment]
Hi @kenman345 

Yup! I have forked your repository and found the issue, looks like your `.travis.yml` configuration was different from what we used to handle, and it caused the structure of the payload we're receiving from Travis to change a bit. 

Anyway, I made the required change, your case definitely helped improving @TravisBuddy, so thanks for that!

I [ran some tests](https://github.com/bluzi/acceptbitcoincash/pull/2#issuecomment-375907795) in order to make sure everything works as expected, but of course test it as well and please let me know if you find any issues.

**Comment by bluzi** [comment]
Closing for now, if you have any more questions let me know.
